export const projects = [
  {
    id: 4,
    slug: "fragments",
    title: "Fragments (Kesit)",
    category: "film",
    year: "2025",
    description: "Original score for the award-winning short film Fragments, a socioeconomical and political standing from the eyes of the youth.",
    image: "/uploads/fragments.jpg",
    awards: ["Best Music - Athens Film Festival", "Official Selection"],
    link: "https://filmfreeway.com/Kesit_",
    // wavFile: "/compositions/fragments/audio.wav",
    // sheetFiles: ["/compositions/fragments/sheet.pdf"],
    // sheetType: "pdf",
    featured: false
  },
  {
    id: 3,
    slug: "residues",
    title: "Residues",
    category: "concert",
    year: "2026",
    description: "Chamber composition for upright piano, two violins, viola, violoncello, and contrabass. An introspective piece exploring texture and silence.",
    image: "/compositions/residues/cover.jpg",
    awards: [],
    link: null,
    wavFile: "/compositions/residues/Residues.wav",
    sheetFiles: ["/compositions/residues/Residues.pdf"],
    sheetType: "pdf",
    featured: true
  },
  {
    id: 1,
    slug: "embers",
    title: "Embers",
    category: "concert",
    year: "2026",
    description: "A film music I made imagining a end of show/final or a battle scene. Combining oboe, piano and strings. Something quiet catches, grows, burns through the orchestra, then falls back to embers..",
    image: "/compositions/embers/cover.png",
    awards: [],
    link: null,
    wavFile: "/compositions/embers/Embers.wav",
    sheetFiles: ["/compositions/embers/Embers.pdf"],
    sheetType: "pdf",
    featured: true
  },
  {
    id: 5,
    slug: "the-interface",
    title: "The Interface",
    category: "game",
    year: "2022",
    description: "Complete soundtrack for The Interface game, featuring atmospheric electronic compositions and dynamic adaptive music systems.",
    image: "/uploads/interface.jpg",
    awards: [],
    link: "https://soundcloud.com/ozan-417880832/sets/interface-game-soundtracks",
  },
  {
    id: 6,
    slug: "carbondale",
    title: "Carbondale",
    category: "film",
    year: "2023",
    description: "Atmospheric orchestral score for the short film Carbondale, for the narrative scene the train departs.",
    image: "/uploads/carbondale.jpeg",
    awards: [],
    link: "https://soundcloud.com/ozan-417880832/carbondale-short-film-soundtrack",
    // wavFile: "/compositions/carbondale/audio.wav",
    // sheetFiles: ["/compositions/carbondale/sheet.pdf"],
    // sheetType: "pdf",
  },
   {
    id: 1,
    slug: "summer",
    title: "Summer",
    category: "concert",
    year: "2026",
    description: "An original Piano composition",
    image: "/compositions/summer/cover.png",
    awards: [],
    link: null,
    wavFile: "/compositions/summer/Summer.wav",
    sheetFiles: ["/compositions/summer/Summer.pdf"],
    sheetType: "pdf",
    featured: true
  }
]

export function getProjectBySlug(slug) {
  return projects.find(p => p.slug === slug) || null
}
